version: '2.1'

services:
  app:
    build:
      context: ./
    command: ['bundle', 'exec', 'shotgun', '-p', '3000', '-o', '0.0.0.0', '/app/config.ru']
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:9.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/10_init.sql:/docker-entrypoint-initdb.d/10_init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

volumes:
  postgres:
