version: '2.1'

services:
  app:
    build:
      context: ./
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:9.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

volumes:
  postgres:
