version: '2.1'

services:
  app:
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:9.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
#      - ./db/10_dump_all_schema.sql:/docker-entrypoint-initdb.d/10_schema.sql
#      - ./db/20_dump_all_data.sql:/docker-entrypoint-initdb.d/20_data.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

volumes:
  postgres:
